###################################################################################
#   _     _                                                            _          #
#  | |__ | |__   __ _  ___ ___  _ __ ___  _ __   ___  _ __   ___ _ __ | |_ ___    #
#  | '_ \| '_ \ / _` |/ __/ _ \| '_ ` _ \| '_ \ / _ \| '_ \ / _ \ '_ \| __/ __|   #
#  | | | | | | | (_| | (_| (_) | | | | | | |_) | (_) | | | |  __/ | | | |_\__ \   #
#  |_| |_|_| |_|\__, |\___\___/|_| |_| |_| .__/ \___/|_| |_|\___|_| |_|\__|___/   #
#               |___/                    |_|                                      #
#                                                                                 #
###################################################################################

pipelines:
  pull-requests:
    '**':
      - step:
          name: Run Jest Test
          image: framgia/laravel-workspace
          script:
            - npm install
            - npm run test
          deployment: test
  branches:
    dev:
      - step:
          name: Deploy storybook to development
          image: framgia/laravel-workspace
          # image: framgiaciteam/deb-deploy:7.3
          script:
            - npm install
            - npm run test
          deployment: staging
    master:
      - step:
          name: Publish component to npm
          image: framgia/laravel-workspace
          # image: framgiaciteam/deb-deploy:7.3
          script:
            - npm install
            - npm set registry "https://registry.npmjs.org/"
            - npm set //registry.npmjs.org/:_authToken=$TOKEN_NPM
            - npm publish
          deployment: production
